### ISSUE TITLE
bug: Warning in topic tests - Event Loop is closed

### ISSUE THREAD

**Issue by Valeria1235** [ydb-platform/ydb-python-sdk#212]
# Bug Report

**YDB GO Python version:** 3.10

**Environment:** v3

**Current behavior:** Test passed with following warnings:
```
.tox/py/lib/python3.10/site-packages/_pytest/config/__init__.py:1233
  /home/waleriya/ydb/ydb-python-sdk/.tox/py/lib/python3.10/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: asyncio_mode
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

ydb/_topic_writer/topic_writer_asyncio_test.py::TestWriterAsyncIOReconnector::test_encode_data_inplace[2-datas1]
  /home/waleriya/ydb/ydb-python-sdk/.tox/py/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object WriterAsyncIOReconnector._read_loop at 0x7fae28d0f300>
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
      await getter
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py", line 520, in _read_loop
      resp = await writer.receive()
    File "/home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio_test.py", line 184, in receive
      item = await self.from_server.get()
    File "/usr/lib/python3.10/asyncio/queues.py", line 161, in get
      getter.cancel()  # Just in case getter is not done yet.
    File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
      self._check_closed()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Expected behavior:** Tests passed without warnings

**Steps to reproduce:** run local tests, for example: `$ tox -e py -- ydb/_topic_writer/`

**Comment by Valeria1235** [comment]
Tests output:

```
Task was destroyed but it is pending!
task: <Task pending name='encode_loop' coro=<WriterAsyncIOReconnector._encode_loop() running at /home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py:398> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='connection_loop' coro=<WriterAsyncIOReconnector._connection_loop() running at /home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py:370> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object WriterAsyncIOReconnector._encode_loop at 0x7f7993be7a00>
Traceback (most recent call last):
  File "/home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py", line 398, in _encode_loop
    messages = await self._messages_for_encode.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 161, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object WriterAsyncIOReconnector._connection_loop at 0x7f7993be7a70>
Traceback (most recent call last):
  File "/home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py", line 393, in _connection_loop
    task.cancel()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='writer send loop' coro=<WriterAsyncIOReconnector._send_loop() running at /home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py:540> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending name='writer receive loop' coro=<WriterAsyncIOReconnector._read_loop() running at /home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py:513> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object WriterAsyncIOReconnector._read_loop at 0x7f7993be7d80>
Traceback (most recent call last):
  File "/home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio.py", line 513, in _read_loop
    resp = await writer.receive()
  File "/home/waleriya/ydb/ydb-python-sdk/ydb/_topic_writer/topic_writer_asyncio_test.py", line 227, in receive
    item = await self.from_server.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 161, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by Valeria1235** [comment]
And in _topic_reader tests same issues
