### ISSUE TITLE
Can't run basic_example_v1

### ISSUE THREAD

**Issue by kiper-prog** [ydb-platform/ydb-python-sdk#34]
```
Traceback (most recent call last):
  File "__main__.py", line 26, in <module>
    basic_example.run(
  File "/home/anikeev/ydb-python-sdk/examples/basic_example_v1/basic_example.py", line 307, in run
    driver.wait(timeout=5, fail_fast=True)
  File "/usr/local/lib/python3.8/dist-packages/ydb/pool.py", line 415, in wait
    self._store.add_fast_fail().result(timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ydb.issues.ConnectionFailure: Failed to resolve endpoints for database /ru-central1/.... Endpoint: ".....ydb.mdb.yandexcloud.net:2135". Error details:
 MetadataUrlCredentials: 404 Client Error: Not Found for url: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token.
Check that metadata service configured properly and application deployed in VM or function at Yandex.Cloud.
```
OS: Ubuntu 20.04.4 LTS
Python 3.8.10

python3 -m pip freeze | grep -E "(protobuf|grpcio|enum-compat)"
enum-compat==0.0.3
grpcio==1.47.0
protobuf==3.20.1

**Comment by RoastedHobnai1** [comment]
If you're running this example from YCloud VM, you can try using an external IP of the database's host instead of FQDN.

**Comment by zinal** [comment]
Please configure the authentication method to be used.
One option could be to use the service account key, which means that:
1. service account needs to be created, with the ydb.editor role
2. service account key file needs to be generated (yc iam key create ...)
3. YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS env var should point to the generated key file name
