### ISSUE TITLE
bug: anonymous_credentials example error with local YDB cluster

### ISSUE THREAD

**Issue by serker72** [ydb-platform/ydb-python-sdk#402]
# Bug Report

**YDB Python SDK version:**

ydb                      3.8.1

**Environment**

Ubuntu 22.04.4 LTS
Python 3.12.2
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 167
model name	: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
stepping	: 1
microcode	: 0x5d
cpu MHz		: 4554.218
cache size	: 16384 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 27
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple shadow_vmcs pml ept_mode_based_exec tsc_scaling
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs mmio_stale_data retbleed eibrs_pbrsb gds
bogomips	: 4992.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

YDB local cluster in docker:
c0700f5ea760   cr.yandex/yc/yandex-docker-local-ydb:latest   "sh ./initialize_loc…"   3 hours ago   Up 3 hours (healthy)   0.0.0.0:2135-2136->2135-2136/tcp, :::2135-2136->2135-2136/tcp, 0.0.0.0:8765->8765/tcp, :::8765->8765/tcp   nolim-cloud-ydb

$ pip list
Package                  Version
------------------------ -----------
aiohttp                  3.9.3
aiosignal                1.3.1
alembic                  1.13.1
annotated-types          0.6.0
anyio                    4.3.0
attrs                    23.2.0
black                    24.3.0
boto3                    1.34.69
botocore                 1.34.69
certifi                  2024.2.2
cffi                     1.16.0
charset-normalizer       3.3.2
classy-fastapi           0.6.1
click                    8.1.7
cryptography             42.0.5
fastapi                  0.110.0
fastapi-jwt-auth2        0.5.0
frozenlist               1.4.1
googleapis-common-protos 1.63.0
greenlet                 3.0.3
grpcio                   1.62.1
gunicorn                 21.2.0
h11                      0.14.0
idna                     3.6
iso8601                  2.1.0
isort                    5.13.2
jmespath                 1.0.1
Mako                     1.3.2
MarkupSafe               2.1.5
multidict                6.0.5
mypy-extensions          1.0.0
packaging                24.0
pathspec                 0.12.1
pip                      24.0
platformdirs             4.2.0
protobuf                 4.25.3
pycparser                2.21
pydantic                 2.6.4
pydantic_core            2.16.3
pydantic-settings        2.2.1
PyJWT                    1.7.1
python-dateutil          2.9.0.post0
python-dotenv            1.0.1
requests                 2.31.0
s3transfer               0.10.1
setuptools               69.1.1
six                      1.16.0
sniffio                  1.3.1
SQLAlchemy               2.0.29
starlette                0.36.3
typing_extensions        4.10.0
urllib3                  2.2.1
uvicorn                  0.29.0
wheel                    0.42.0
yandexcloud              0.269.0
yarl                     1.9.4
ydb                      3.8.1
ydb-sqlalchemy           0.0.1b11

**Current behavior:**

$ export YDB_ANONYMOUS_CREDENTIALS=1
$ export YDB_ENDPOINT=grpc://localhost:2136
$ export YDB_DATABASE=/local
$ python examples/ydb/anonymous_credentials.py 
INFO:ydb.connection:Closing channel for endpoint c0700f5ea760:2136
INFO:ydb.connection:Closing channel for endpoint localhost:2136
INFO:ydb.connection:Closing channel for endpoint localhost:2136
INFO:ydb.pool.Discovery:Successfully terminated discovery process
Traceback (most recent call last):
  File "/home/serg/projects/softorium/nolim-cloud-backend/examples/ydb/anonymous_credentials.py", line 32, in <module>
    main()
  File "/home/serg/projects/softorium/nolim-cloud-backend/examples/ydb/anonymous_credentials.py", line 26, in main
    driver.wait(fail_fast=True, timeout=60)
  File "/media/serg/data/virtualenvs/nolim-cloud/lib/python3.12/site-packages/ydb/pool.py", line 392, in wait
    self._store.add_fast_fail().result(timeout)
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
ydb.issues.ConnectionFailure: Resolved endpoints for database /local: DiscoveryResult <self_location: 1, endpoints [<Endpoint c0700f5ea760:2136, location 1, ssl: False>]>

**Other information:**

The request in the container console is processed successfully.
The request via the web interface is processed successfully.
![ydb_container_console](https://github.com/ydb-platform/ydb-python-sdk/assets/12747636/65caee72-c12f-4d62-b664-db704c2da224)
![ydb_container_web](https://github.com/ydb-platform/ydb-python-sdk/assets/12747636/df6dd5fa-fa95-46b9-bd62-22b47fe0534a)

**Comment by rekby** [comment]
Hello, thanks for the report.
I will check it.

**Comment by vladkolotvin** [comment]
have same issue

**Comment by vgvoleg** [comment]
This is a local-YDB Docker networking issue, not an SDK bug.

Discovery **succeeded** but returned the container's internal hostname as the serving endpoint: `endpoints [<Endpoint c0700f5ea760:2136 ...>]`. `c0700f5ea760` is the container's own hostname, unreachable from the host, so the driver correctly failed to connect to the advertised endpoint. The SDK connects to whatever endpoints the cluster advertises via `ListEndpoints` — here the cluster advertised an unreachable address.

Verified on a correctly-configured local YDB that advertises `localhost:2136`: discovery returns `<Endpoint localhost:2136>` and `examples/anonymous-credentials/main.py` runs green (exit 0). So the example is correct; the difference is purely what the container advertises.

Two ways to resolve:
1. **`disable_discovery=True`** in `DriverConfig` (added in 3.21.2) — pins the endpoint you pass and skips discovery, so the advertised internal hostname is never used.
2. Run the YDB container so it advertises a host-reachable address (host networking, or set the container's public gRPC host/hostname to one the host can reach).

Closing as an environment/config issue — happy to reopen if you see a genuine discovery/connect failure against a cluster that advertises a reachable endpoint.
