### ISSUE TITLE
bug: 'builtin_function_or_method' object has no attribute 'call_soon'

### ISSUE THREAD

**Issue by peppa-pigfarm** [ydb-platform/ydb-python-sdk#506]
# Bug Report

**YDB Python SDK version:**

3.18.13

**Environment**

Linux / 3.12.7 / arm64

**Current behavior:**

```
Exception ignored in: <function TableClient.__del__ at 0xffff835fb560>
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/ydb/aio/table.py", line 157, in __del__
    asyncio.get_running_loop.call_soon(self._stop_pool_if_needed)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'call_soon'
Exception ignored in: <function TableClient.__del__ at 0xffff835fb560>
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/ydb/aio/table.py", line 157, in __del__
    asyncio.get_running_loop.call_soon(self._stop_pool_if_needed)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'call_soon'
Exception ignored in: <function TableClient.__del__ at 0xffff835fb560>
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/ydb/aio/table.py", line 157, in __del__
    asyncio.get_running_loop.call_soon(self._stop_pool_if_needed)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'call_soon'
Exception ignored in: <function TableClient.__del__ at 0xffff835fb560>
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/ydb/aio/table.py", line 157, in __del__
    asyncio.get_running_loop.call_soon(self._stop_pool_if_needed)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
**Expected behavior:**

no errors

**Comment by vgvoleg** [comment]
Fixed in v3.18.8 (commit 543fe08, "Refactor aio tableclient destructor"). `TableClient.__del__` now calls `asyncio.get_running_loop().create_task(...)` (with the missing parentheses) inside a `try/except`, so the `AttributeError: 'builtin_function_or_method' object has no attribute 'call_soon'` can no longer occur. Please upgrade to a current release. Closing as resolved.
